@baseUrl = http://localhost:1337/api/v1


### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}


### Login
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}


### Ruta protegida
GET http://localhost:1337/health
Authorization: Bearer {{loginRequest.response.body.token}}


### Chat con la IA
POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "message": "¿Cuáles son las mejores criptomonedas para invertir a largo plazo?"
}


### Chat con mercado tradicional
POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "message": "¿Cómo están las principales acciones del mercado hoy?"
}


### Pregunta fuera de tema
POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "message": "¿Quién ganó el mundial 2022?"
}

### Estrategia de inversión a largo plazo
POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "message": "¿Cuál sería una buena estrategia de inversión a largo plazo combinando acciones y criptomonedas?"
}


### Obtener todos los chats
GET {{baseUrl}}/history
Authorization: Bearer {{loginRequest.response.body.token}}

### Obtener todos los chats de un usuario
GET {{baseUrl}}/user-history
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "user": {"userId": "6a26fd881c17ea2c546892dd"}
}

### Obtener todos los chats de otro usuario
GET {{baseUrl}}/user-history
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "user": {"userId": "6a29dd49796a2ef5cdc44bea"}
}

### Obtener todos los chats de otro otro usuario
GET {{baseUrl}}/user-history
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "user": {"userId": "6a29f3b87719c721d5aa3d9c"}
}

### Obtener un chat según id
GET {{baseUrl}}/history/6a29c738f9c2aad887299413
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

### Obtener últimos chat de un usuario según id
GET {{baseUrl}}/user-last-history/
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "user": {"userId": "6a26fd881c17ea2c546892dd"}
}

### Eliminar un chat de un usuario según id
DELETE {{baseUrl}}/user-history/6a29c5296ea7e91a3e89bd0b
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "user": {"userId": "6a26fd881c17ea2c546892dd"}
}

### Eliminar todos los chats de un usuario
DELETE {{baseUrl}}/user-history/
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "user": {"userId": "6a26fd881c17ea2c546892dd"}
}